"""Add term_hash to SearchTerm

Revision ID: 0d38d4b62f18
Revises: a71ce24f3b51
Create Date: 2025-08-01 14:06:10.321417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d38d4b62f18'
down_revision: Union[str, Sequence[str], None] = 'a71ce24f3b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
