"""Initial migration

Revision ID: a406df25cdab
Revises: 
Create Date: 2025-08-01 11:03:09.593419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a406df25cdab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_terms_id'), 'search_terms', ['id'], unique=False)
    op.create_index(op.f('ix_search_terms_term'), 'search_terms', ['term'], unique=False)
    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('search_term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['search_term_id'], ['search_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_content_id'), 'generated_content', ['id'], unique=False)
    op.create_table('generated_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('search_term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['search_term_id'], ['search_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_keywords_id'), 'generated_keywords', ['id'], unique=False)
    op.create_table('sentiment_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('readability', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('search_term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['search_term_id'], ['search_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_analysis_id'), 'sentiment_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_analysis_id'), table_name='sentiment_analysis')
    op.drop_table('sentiment_analysis')
    op.drop_index(op.f('ix_generated_keywords_id'), table_name='generated_keywords')
    op.drop_table('generated_keywords')
    op.drop_index(op.f('ix_generated_content_id'), table_name='generated_content')
    op.drop_table('generated_content')
    op.drop_index(op.f('ix_search_terms_term'), table_name='search_terms')
    op.drop_index(op.f('ix_search_terms_id'), table_name='search_terms')
    op.drop_table('search_terms')
    # ### end Alembic commands ###
