"""alembic migration

Revision ID: a71ce24f3b51
Revises: 51ad74afdd9b
Create Date: 2025-08-01 13:53:23.775361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71ce24f3b51'
down_revision: Union[str, Sequence[str], None] = '51ad74afdd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_terms', sa.Column('term_hash', sa.String(length=64), nullable=True))
    op.alter_column('search_terms', 'term',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_search_terms_term'), table_name='search_terms')
    op.create_index(op.f('ix_search_terms_term_hash'), 'search_terms', ['term_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_terms_term_hash'), table_name='search_terms')
    op.create_index(op.f('ix_search_terms_term'), 'search_terms', ['term'], unique=False)
    op.alter_column('search_terms', 'term',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('search_terms', 'term_hash')
    # ### end Alembic commands ###
